---
- name: Set facts for Java 11 vars
  set_fact:
    java_home: "/opt/jdk/{{ java_jdk_version }}"
  tags: java
  - name: Upload .tar.gz file containing binaries from local storage
    copy:
      src: "{{ java_oracle_jdk_package }}"
      dest: "/tmp/jdk-{{ java_jdk_version }}.tar.gz"
    register: download_java_binaries
    until: download_java_binaries is succeeded
    tags: java
  - name: Ensure installation dir exists
    file:
      state: directory
      path: "{{ java_home }}"
    tags: java
  - name: Extract java in the installation directory
    unarchive:
      copy: false
      src: "/tmp/jdk-{{ java_jdk_version }}.tar.gz"
      dest: "{{ java_home }}"
      extra_opts: [--strip-components=1]
      creates: "{{ java_home }}/bin/java"
    tags:
      - java
